name: image_compare_2
description: Package maintained based on image_compare. Compare images using a variety of algorithms.
repository: https://github.com/lcuis/image_compare
version: 1.1.3

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  image: '>=3.0.0 <5.0.0'
  universal_io: '>=2.0.0 <4.0.0'

dev_dependencies:
  lints: '>=1.0.0 <4.0.0'

assets:
  - images/
