name: image_compare
description: Dart package for image comparison. Compare images for difference using a variety of algorithms.
repository: https://github.com/nitinramadoss/image_compare
version: 1.1.2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  image: ^3.0.0
  universal_io: ^2.0.0

dev_dependencies:
  pedantic: ^1.9.0

assets:
  - assets/
  - assets/drawings/
  - assets/animals/
  - assets/objects/
